services:
  - type: web
    name: diet-app-backend
    env: docker
    dockerFilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: PORT
        value: 8000
